### ISSUE TITLE
Same phone number for multiple users

### ISSUE THREAD

**Issue by meilon** [znuny/Znuny4OTRS-CTI#3] opened 2015-07-13 12:10 UTC
When opening the URL otrs/index.pl?Action=AgentTicketPhoneCTI;CallerID=123, and in the system are more than one user with that phone number, I should either be asked for whom the ticket should be created (my preference) or all users with that matching phone number.

Right now only the first result is added.

**Comment by thorsteneckel** [comment] 2015-07-13 16:54
Hi @meilon,
thanks for your request. I validated your request and you are right. currently the last CustomerUserID in alphabetic order is taken as the only CustomerUser.
I already have solution for this. I will validate it tomorrow and give you feedback on this.

**Comment by thorsteneckel** [comment] 2015-07-14 09:33
Hi @meilon,
I validated my solution and it works for me. If a CallerID is assigned to multiple users all of them get added to the Ticket create screen. If the CustomerInformationCenter SysConfig is enabled the old logic still takes place.
The issue is fixed in Znuny4OTRS-CTI version 1.2.2.
Please let me know if it works for you, too.

**Closed as completed by thorsteneckel** 2015-07-14 09:33 UTC
